export enum FILE_OPERATIONS {
    UPLOAD_FILES = 'UPLOAD_FILES',
    DELETE_FILE = 'DELETE_FILE',
    DOWNLOAD_ZIP = 'DOWNLOAD_ZIP',
    GET_FILE_TREE = 'GET_FILE_TREE',
    CHECK_IF_EXISTS = 'CHECK_IF_EXISTS',
}

export enum FILE_ENTITIES {
    PRIMARY_TASK_FILES = 'PrimaryTask',
    FINANCIAL_TASK_FILES = 'taskConfigFiles'
}