export enum ConfigKeys {
    TASK_STATUS = 'taskStatus',
    BILLING_AND_INVOICING = 'billingAndInvoicing',
    TASK_DOC_TYPE = 'taskDocType',
    TASK_UPDATE_REASONS = 'taskUpdateReasons',
    USER_ROLES = 'userRoles',
    USER_DESIGNATIONS = 'userDesignations',
    CLIENT_CATEGORY = 'clientCategory',
    INVOICE_UPDATE_REASONS = 'invoiceUpdateReasons',
    LICENSED_MODULES = 'licensedModules',
    TOTAL_USER_LEAVES = 'totalUserLeaves',
    PERMISSIONS = 'permissions',
    DROP_DOWNS = 'drop_downs',
    APPS = 'apps',
    AUDITS_TABLE_COLUMNS = 'auditsTableColumns',
    FILTERS = 'filters',
    CONFIGURATION_LIST = 'configurationList',
    TASK_CATEGORY = 'taskCategory',
    APPS_AND_PERMISSION_ROLES = 'appsAndpermissionRoles',
    HSN_SAC_CODE_CONFIGURATION = 'hsnSacCodeConfiguration',
    NOTIFICATIONS = 'notifications',
    EVENT_HISTORY = 'eventHistory'
}